#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output HDMI-A-0 --primary  --auto &

bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 9 0 

bspc config border_width         2
bspc config window_gap           3

bspc config normal_border_color "#C3BAC6"
bspc config focused_border_color "#DDB6F2"

bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#Mice bindings
#   Set mouse 1 to move floating windows
bspc config pointer_action1 move

#   Mouse 2 button resizes the window by side
bspc config pointer_action2 resize_side

#   Mouse 3 button (right mouse) resize by corner
bspc config pointer_action2 resize_corner

#AutoStart
xrdb .Xresources
#Wallpapers
feh --bg-fill --randomize ~/Pictures/Wallpapers/astrounaut.jpg
$HOME/.config/polybar/launch.sh &

# setxkbmap -layout br -variant abnt2 
setxkbmap -option caps:none

# caps lock to multi End key
xmodmap -e "keycode 66 = Multi_key End"

/usr/bin/emacs --daemon &
